// This file is generated by Supabase CLI.
// Regenerate it with: `npm run supabase:types`
//
// NOTE: This placeholder exists so TypeScript can compile before you've
// generated real types. Running the generation command will overwrite it.

export type Database = any;
